stages:
  - deploy

variables:
  DOCKER_COMPOSE_FILE: docker-compose.yml

deploy-job:
  stage: deploy
  tags:
    - self-hosted-runner
  script:
    - docker compose -f $DOCKER_COMPOSE_FILE down
    - docker compose -f $DOCKER_COMPOSE_FILE build --no-cache
    - docker compose -f $DOCKER_COMPOSE_FILE up -d
  environment:
    name: production
